name: test-code
env:
  PYTHON_VERSION: "3.12"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      PYTHONPATH: "./src"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r tests/requirements.txt
          pip install -r ./requirements.txt

      - name: Test with pytest
        run: pytest
